
spring:
  application:
    name: eazyschool
  profiles:
    active: development
  thymeleaf:
    cache: false
  security:
    user:
      name: "wolf"
      password: 1234

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/eazyschool
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8085
#  servlet:
#    context-path: /eazyschool

logging:
  level:
    com.marcusvbrangel.eazyschool: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

debug: false
